<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

use \ArrayAccess;

/**
 * InventoryCount Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://squareup.com/developers
 */
class InventoryCount implements ArrayAccess
{
    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    public static $swaggerTypes = [
        'catalog_object_id' => 'string',
        'catalog_object_type' => 'string',
        'status' => 'string',
        'location_id' => 'string',
        'quantity' => 'string',
        'calculated_at' => 'string'
    ];

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    public static $attributeMap = [
        'catalog_object_id' => 'catalog_object_id',
        'catalog_object_type' => 'catalog_object_type',
        'status' => 'status',
        'location_id' => 'location_id',
        'quantity' => 'quantity',
        'calculated_at' => 'calculated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    public static $setters = [
        'catalog_object_id' => 'setCatalogObjectId',
        'catalog_object_type' => 'setCatalogObjectType',
        'status' => 'setStatus',
        'location_id' => 'setLocationId',
        'quantity' => 'setQuantity',
        'calculated_at' => 'setCalculatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    public static $getters = [
        'catalog_object_id' => 'getCatalogObjectId',
        'catalog_object_type' => 'getCatalogObjectType',
        'status' => 'getStatus',
        'location_id' => 'getLocationId',
        'quantity' => 'getQuantity',
        'calculated_at' => 'getCalculatedAt'
    ];

    /**
     * $catalog_object_id The id of the [CatalogObject](#type-catalogobject) being tracked.
     * @var string
     */
    private $catalog_object_id;
    /**
     * $catalog_object_type The type of the object being tracked, e.g., `\"ITEM_VARIATION\"`.
     * @var string
     */
    private $catalog_object_type;
    /**
     * $status The current [InventoryStatus](#type-inventorystatus) of the object.
     * @var string
     */
    private $status;
    /**
     * $location_id The id of the [Location](#type-location) where the object is being tracked.
     * @var string
     */
    private $location_id;
    /**
     * $quantity The quantity of the object as a decimal string. Fractional quantities are not currently supported.
     * The database will truncate fractional values smaller than 1/100,000 when fractional values are supported.
     * @var string
     */
    private $quantity;
    /**
     * $calculated_at Read-only time of the most recent physical count or adjustment that had an affect on the given
     * product/status/location/quantity tuple.
     * @var string
     */
    private $calculated_at;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initializing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            if (isset($data["catalog_object_id"])) {
                $this->catalog_object_id = $data["catalog_object_id"];
            } else {
                $this->catalog_object_id = null;
            }
            if (isset($data["catalog_object_type"])) {
                $this->catalog_object_type = $data["catalog_object_type"];
            } else {
                $this->catalog_object_type = null;
            }
            if (isset($data["status"])) {
                $this->status = $data["status"];
            } else {
                $this->status = null;
            }
            if (isset($data["location_id"])) {
                $this->location_id = $data["location_id"];
            } else {
                $this->location_id = null;
            }
            if (isset($data["quantity"])) {
                $this->quantity = $data["quantity"];
            } else {
                $this->quantity = null;
            }
            if (isset($data["calculated_at"])) {
                $this->calculated_at = $data["calculated_at"];
            } else {
                $this->calculated_at = null;
            }
        }
    }

    /**
     * Gets catalog_object_id
     * @return string
     */
    public function getCatalogObjectId()
    {
        return $this->catalog_object_id;
    }

    /**
     * Sets catalog_object_id
     * @param string $catalog_object_id The id of the [CatalogObject](#type-catalogobject) being tracked.
     * @return $this
     */
    public function setCatalogObjectId($catalog_object_id)
    {
        $this->catalog_object_id = $catalog_object_id;
        return $this;
    }

    /**
     * Gets catalog_object_type
     * @return string
     */
    public function getCatalogObjectType()
    {
        return $this->catalog_object_type;
    }

    /**
     * Sets catalog_object_type
     * @param string $catalog_object_type The type of the object being tracked, e.g., `\"ITEM_VARIATION\"`.
     * @return $this
     */
    public function setCatalogObjectType($catalog_object_type)
    {
        $this->catalog_object_type = $catalog_object_type;
        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status
     * @param string $status The current [InventoryStatus](#type-inventorystatus) of the object.
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Gets location_id
     * @return string
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Sets location_id
     * @param string $location_id The id of the [Location](#type-location) where the object is being tracked.
     * @return $this
     */
    public function setLocationId($location_id)
    {
        $this->location_id = $location_id;
        return $this;
    }

    /**
     * Gets quantity
     * @return string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Sets quantity
     * @param string $quantity The quantity of the object as a decimal string. Fractional quantities are not currently
     * supported. The database will truncate fractional values smaller than 1/100,000 when fractional values are
     * supported.
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * Gets calculated_at
     * @return string
     */
    public function getCalculatedAt()
    {
        return $this->calculated_at;
    }

    /**
     * Sets calculated_at
     * @param string $calculated_at Read-only time of the most recent physical count or adjustment that had an affect
     * on the given product/status/location/quantity tuple.
     * @return $this
     */
    public function setCalculatedAt($calculated_at)
    {
        $this->calculated_at = $calculated_at;
        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed $value Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
