<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SquareConnect\Model;

use \ArrayAccess;

/**
 * InventoryPhysicalCount Class Doc Comment
 *
 * @category Class
 * @package  SquareConnect
 * @author   Square Inc.
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://squareup.com/developers
 */
class InventoryPhysicalCount implements ArrayAccess
{
    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    public static $swaggerTypes = [
        'id' => 'string',
        'reference_id' => 'string',
        'catalog_object_id' => 'string',
        'catalog_object_type' => 'string',
        'status' => 'string',
        'location_id' => 'string',
        'quantity' => 'string',
        'source' => \SquareConnect\Model\SourceApplication::class,
        'employee_id' => 'string',
        'occurred_at' => 'string',
        'created_at' => 'string'
    ];

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    public static $attributeMap = [
        'id' => 'id',
        'reference_id' => 'reference_id',
        'catalog_object_id' => 'catalog_object_id',
        'catalog_object_type' => 'catalog_object_type',
        'status' => 'status',
        'location_id' => 'location_id',
        'quantity' => 'quantity',
        'source' => 'source',
        'employee_id' => 'employee_id',
        'occurred_at' => 'occurred_at',
        'created_at' => 'created_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    public static $setters = [
        'id' => 'setId',
        'reference_id' => 'setReferenceId',
        'catalog_object_id' => 'setCatalogObjectId',
        'catalog_object_type' => 'setCatalogObjectType',
        'status' => 'setStatus',
        'location_id' => 'setLocationId',
        'quantity' => 'setQuantity',
        'source' => 'setSource',
        'employee_id' => 'setEmployeeId',
        'occurred_at' => 'setOccurredAt',
        'created_at' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    public static $getters = [
        'id' => 'getId',
        'reference_id' => 'getReferenceId',
        'catalog_object_id' => 'getCatalogObjectId',
        'catalog_object_type' => 'getCatalogObjectType',
        'status' => 'getStatus',
        'location_id' => 'getLocationId',
        'quantity' => 'getQuantity',
        'source' => 'getSource',
        'employee_id' => 'getEmployeeId',
        'occurred_at' => 'getOccurredAt',
        'created_at' => 'getCreatedAt'
    ];

    /**
     * $id The unique ID generated by Square's servers for this [InventoryPhysicalCount](#type-inventoryphysicalcount).
     * @var string
     */
    private $id;
    /**
     * $reference_id An optional id to tie this [InventoryPhysicalCount](#type-inventoryphysicalcount) to an external
     * system.
     * @var string
     */
    private $reference_id;
    /**
     * $catalog_object_id The id of the [CatalogObject](#type-catalogobject) being tracked.
     * @var string
     */
    private $catalog_object_id;
    /**
     * $catalog_object_type The type of the object being tracked generated by Square's servers, e.g.,
     * `\"ITEM_VARIATION\"`.
     * @var string
     */
    private $catalog_object_type;
    /**
     * $status The current [InventoryStatus](#type-inventorystatus) of the object.
     * @var string
     */
    private $status;
    /**
     * $location_id The id of the [Location](#type-location) where the object is being tracked.
     * @var string
     */
    private $location_id;
    /**
     * $quantity The quantity of the object as a decimal string. Fractional quantities are not currently supported.
     * The database will truncate fractional values smaller than 1/100,000 when fractional values are supported.
     * @var string
     */
    private $quantity;
    /**
     * $source The calling application.
     * @var \SquareConnect\Model\SourceApplication
     */
    private $source;
    /**
     * $employee_id The id of the [Employee](#type-employee) responsible for the physical count.
     * @var string
     */
    private $employee_id;
    /**
     * $occurred_at The time associated with the physical count, in RFC 3339 format. On writes, cannot be older than
     * 24 hours or in the future.
     * @var string
     */
    private $occurred_at;
    /**
     * $created_at Read-only time when the server received this physical count information, in RFC 3339 format.
     * @var string
     */
    private $created_at;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initializing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            if (isset($data["id"])) {
                $this->id = $data["id"];
            } else {
                $this->id = null;
            }
            if (isset($data["reference_id"])) {
                $this->reference_id = $data["reference_id"];
            } else {
                $this->reference_id = null;
            }
            if (isset($data["catalog_object_id"])) {
                $this->catalog_object_id = $data["catalog_object_id"];
            } else {
                $this->catalog_object_id = null;
            }
            if (isset($data["catalog_object_type"])) {
                $this->catalog_object_type = $data["catalog_object_type"];
            } else {
                $this->catalog_object_type = null;
            }
            if (isset($data["status"])) {
                $this->status = $data["status"];
            } else {
                $this->status = null;
            }
            if (isset($data["location_id"])) {
                $this->location_id = $data["location_id"];
            } else {
                $this->location_id = null;
            }
            if (isset($data["quantity"])) {
                $this->quantity = $data["quantity"];
            } else {
                $this->quantity = null;
            }
            if (isset($data["source"])) {
                $this->source = $data["source"];
            } else {
                $this->source = null;
            }
            if (isset($data["employee_id"])) {
                $this->employee_id = $data["employee_id"];
            } else {
                $this->employee_id = null;
            }
            if (isset($data["occurred_at"])) {
                $this->occurred_at = $data["occurred_at"];
            } else {
                $this->occurred_at = null;
            }
            if (isset($data["created_at"])) {
                $this->created_at = $data["created_at"];
            } else {
                $this->created_at = null;
            }
        }
    }

    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id
     * @param string $id The unique ID generated by Square's servers for this
     * [InventoryPhysicalCount](#type-inventoryphysicalcount).
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * Gets reference_id
     * @return string
     */
    public function getReferenceId()
    {
        return $this->reference_id;
    }

    /**
     * Sets reference_id
     * @param string $reference_id An optional id to tie this [InventoryPhysicalCount](#type-inventoryphysicalcount)
     * to an external system.
     * @return $this
     */
    public function setReferenceId($reference_id)
    {
        $this->reference_id = $reference_id;
        return $this;
    }

    /**
     * Gets catalog_object_id
     * @return string
     */
    public function getCatalogObjectId()
    {
        return $this->catalog_object_id;
    }

    /**
     * Sets catalog_object_id
     * @param string $catalog_object_id The id of the [CatalogObject](#type-catalogobject) being tracked.
     * @return $this
     */
    public function setCatalogObjectId($catalog_object_id)
    {
        $this->catalog_object_id = $catalog_object_id;
        return $this;
    }

    /**
     * Gets catalog_object_type
     * @return string
     */
    public function getCatalogObjectType()
    {
        return $this->catalog_object_type;
    }

    /**
     * Sets catalog_object_type
     * @param string $catalog_object_type The type of the object being tracked generated by Square's servers, e.g.,
     * `\"ITEM_VARIATION\"`.
     * @return $this
     */
    public function setCatalogObjectType($catalog_object_type)
    {
        $this->catalog_object_type = $catalog_object_type;
        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status
     * @param string $status The current [InventoryStatus](#type-inventorystatus) of the object.
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Gets location_id
     * @return string
     */
    public function getLocationId()
    {
        return $this->location_id;
    }

    /**
     * Sets location_id
     * @param string $location_id The id of the [Location](#type-location) where the object is being tracked.
     * @return $this
     */
    public function setLocationId($location_id)
    {
        $this->location_id = $location_id;
        return $this;
    }

    /**
     * Gets quantity
     * @return string
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Sets quantity
     * @param string $quantity The quantity of the object as a decimal string. Fractional quantities are not currently
     * supported. The database will truncate fractional values smaller than 1/100,000 when fractional values are
     * supported.
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
        return $this;
    }

    /**
     * Gets source
     * @return \SquareConnect\Model\SourceApplication
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Sets source
     * @param \SquareConnect\Model\SourceApplication $source The calling application.
     * @return $this
     */
    public function setSource($source)
    {
        $this->source = $source;
        return $this;
    }

    /**
     * Gets employee_id
     * @return string
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     * Sets employee_id
     * @param string $employee_id The id of the [Employee](#type-employee) responsible for the physical count.
     * @return $this
     */
    public function setEmployeeId($employee_id)
    {
        $this->employee_id = $employee_id;
        return $this;
    }

    /**
     * Gets occurred_at
     * @return string
     */
    public function getOccurredAt()
    {
        return $this->occurred_at;
    }

    /**
     * Sets occurred_at
     * @param string $occurred_at The time associated with the physical count, in RFC 3339 format. On writes, cannot be
     * older than 24 hours or in the future.
     * @return $this
     */
    public function setOccurredAt($occurred_at)
    {
        $this->occurred_at = $occurred_at;
        return $this;
    }

    /**
     * Gets created_at
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Sets created_at
     * @param string $created_at Read-only time when the server received this physical count information, in RFC 3339
     * format.
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed $value Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\SquareConnect\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
